version: "3.3"
services:
  build_env:
    build: "."
    container_name: "service_discovery_dwc"
    image: "service_discovery_dwi"
    volumes:
      - ../:/home/docker/workspace
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    environment:
      - DISPLAY=:0
    stdin_open: true 
    tty: true
    privileged: true
